import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
// import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" data-theme="dark">
        <body
          className={`w-full h-[100svh] flex flex-col items-center antialiased`}
        >
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
